AWSTemplateFormatVersion: '2010-09-09'
Description: Security groups for Gofer OpenSearch integration

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where the security groups will be created

Resources:
  OpenSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for OpenSearch domain
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          Description: HTTPS access from Lambda functions
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: gofer-opensearch-sg

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions accessing OpenSearch
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: gofer-lambda-sg

Outputs:
  OpenSearchSecurityGroupId:
    Description: ID of the OpenSearch security group
    Value: !Ref OpenSearchSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-OpenSearchSG"

  LambdaSecurityGroupId:
    Description: ID of the Lambda security group
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-LambdaSG"
