name: Gofer Project Board Automation

on:
  issues:
    types: [opened, closed]

jobs:
  add-to-backlog:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Backlog
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project: "Gofer Project Board"
          column: "Backlog"
          issue-number: ${{ github.event.issue.number }}

  move-to-done:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Done
        uses: peter-evans/move-project-card@v2
        with:
          project: "Gofer Project Board"
          column: "Done"
          issue-number: ${{ github.event.issue.number }}
